In [5]:
import numpy as np
import pandas as pd
from abd_helper import *
from abd_models import *
from sklearn.metrics import balanced_accuracy_score, accuracy_score, confusion_matrix,classification_report
from constants import *
from helpers import *
from loader import *
from plot import *
import matplotlib.pyplot as plt
import random
import math

In [2]:
#partition 49 patients to 39 train 10 test - random seed done once
trainIDs=[25, 34, 6, 12, 21, 39, 8, 29, 13, 45, 36, 19, 20, 3, 26, 18, 24, 27, 1, 46, 11, 5, 10, 23, 30, 0, 47, 41, 14, 22, 31, 35, 37, 48, 49,15, 17, 4, 32, 44]
testIDs=[]
for i in range(49):
    if i not in trainIDs:
        testIDs.append(i)
print(trainIDs)
print(testIDs)

[25, 34, 6, 12, 21, 39, 8, 29, 13, 45, 36, 19, 20, 3, 26, 18, 24, 27, 1, 46, 11, 5, 10, 23, 30, 0, 47, 41, 14, 22, 31, 35, 37, 48, 49, 15, 17, 4, 32, 44]
[2, 7, 9, 16, 28, 33, 38, 40, 42, 43]


In [3]:
accuracy_of_radar=np.zeros(50)
accuracy_of_mat=np.zeros(50)
for i in range(len(PARTICIPANT_IDS)):
    the_ID=PARTICIPANT_IDS[i]
    the_ss=read_patient_data(the_ID)
    accuracy_of_radar[i]=balanced_accuracy_score(the_ss["sleep_stage_num_psg"],the_ss["sleep_stage_num_somnofy"])
    accuracy_of_mat[i]=balanced_accuracy_score(the_ss["sleep_stage_num_psg"],the_ss["sleep_stage_num_emfit"])
print("Radar:",np.mean(accuracy_of_radar)) 
print("Mat:",np.mean(accuracy_of_mat)) 

Radar: 0.59779158800528
Mat: 0.3788636814128718


C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")


In [21]:
accuracy_of_radar_0=np.zeros(50)
accuracy_of_radar_1=np.zeros(50)
accuracy_of_radar_2=np.zeros(50)
accuracy_of_radar_3=np.zeros(50)
accuracy_of_mat_0=np.zeros(50)
accuracy_of_mat_1=np.zeros(50)
accuracy_of_mat_2=np.zeros(50)
accuracy_of_mat_3=np.zeros(50)

f1_of_radar_0=np.zeros(50)
f1_of_radar_1=np.zeros(50)
f1_of_radar_2=np.zeros(50)
f1_of_radar_3=np.zeros(50)
f1_of_mat_0=np.zeros(50)
f1_of_mat_1=np.zeros(50)
f1_of_mat_2=np.zeros(50)
f1_of_mat_3=np.zeros(50)

for i in range(len(PARTICIPANT_IDS)):
    ss_random=read_patient_data(PARTICIPANT_IDS[i])
    accuracy_radar=classification_report(ss_random["sleep_stage_num_psg"], ss_random["sleep_stage_num_somnofy"],output_dict=True)
    accuracy_of_radar_0[i]=accuracy_radar['0.0']['precision']
    f1_of_radar_0[i]=accuracy_radar['0.0']['f1-score']
    accuracy_of_radar_1[i]=accuracy_radar['1.0']['precision']
    f1_of_radar_1[i]=accuracy_radar['1.0']['f1-score']
    accuracy_of_radar_2[i]=accuracy_radar['2.0']['precision']
    f1_of_radar_2[i]=accuracy_radar['2.0']['f1-score']
    accuracy_of_radar_3[i]=accuracy_radar['3.0']['precision']
    f1_of_radar_3[i]=accuracy_radar['3.0']['f1-score']
    
    accuracy_mat=classification_report(ss_random["sleep_stage_num_psg"], ss_random["sleep_stage_num_emfit"],output_dict=True)
    accuracy_of_mat_0[i]=accuracy_mat['0.0']['precision']
    f1_of_mat_0[i]=accuracy_mat['0.0']['f1-score']
    accuracy_of_mat_1[i]=accuracy_mat['1.0']['precision']
    f1_of_mat_1[i]=accuracy_mat['1.0']['f1-score']
    accuracy_of_mat_2[i]=accuracy_mat['2.0']['precision']
    f1_of_mat_2[i]=accuracy_mat['2.0']['f1-score']
    accuracy_of_mat_3[i]=accuracy_mat['3.0']['precision']
    f1_of_mat_3[i]=accuracy_mat['3.0']['f1-score']

C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metr

C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ab_ay\anaconda3\lib\site-packages\sklearn\metrics\_cla

In [23]:
print("Accuracy when Radar 0 :",np.mean(accuracy_of_radar_0)) 
print("Accuracy when Radar 1 :",np.mean(accuracy_of_radar_1))
print("Accuracy when Radar 2 :",np.mean(accuracy_of_radar_2))
print("Accuracy when Radar 3 :",np.mean(accuracy_of_radar_3))
print("Accuracy when Mat 0 :",np.mean(accuracy_of_mat_0))
print("Accuracy when Mat 1 :",np.mean(accuracy_of_mat_1))
print("Accuracy when Mat 2 :",np.mean(accuracy_of_mat_2))
print("Accuracy when Mat 3 :",np.mean(accuracy_of_mat_3))
print("F1-Score when Radar 0 :",np.mean(f1_of_radar_0))
print("F1-Score when Radar 1 :",np.mean(f1_of_radar_1)) 
print("F1-Score when Radar 2 :",np.mean(f1_of_radar_2)) 
print("F1-Score when Radar 3 :",np.mean(f1_of_radar_3)) 
print("F1-Score when Mat 0 :",np.mean(f1_of_mat_0)) 
print("F1-Score when Mat 1 :",np.mean(f1_of_mat_1)) 
print("F1-Score when Mat 2 :",np.mean(f1_of_mat_2)) 
print("F1-Score when Mat 3 :",np.mean(f1_of_mat_3)) 

Accuracy when Radar 0 : 0.6605537432955082
Accuracy when Radar 1 : 0.4690663871382732
Accuracy when Radar 2 : 0.6742069429466601
Accuracy when Radar 3 : 0.6367602770848496
Accuracy when Mat 0 : 0.4649151770907012
Accuracy when Mat 1 : 0.2436267097461037
Accuracy when Mat 2 : 0.5517184400437473
Accuracy when Mat 3 : 0.36612978061850576
F1-Score when Radar 0 : 0.502687868883173
F1-Score when Radar 1 : 0.5003585225154974
F1-Score when Radar 2 : 0.65202426044821
F1-Score when Radar 3 : 0.5875168786737547
F1-Score when Mat 0 : 0.15347713747905714
F1-Score when Mat 1 : 0.2861660480796011
F1-Score when Mat 2 : 0.5724827190578213
F1-Score when Mat 3 : 0.3624103451377963


In [3]:
max_len=0
min_len=1400
for i in trainIDs:
    subjectID = PARTICIPANT_IDS[i]
    sleep = read_patient_data(subjectID)
    length=len(sleep["sleep_stage_num_psg"].values)
    if max_len<length:
        max_len=length
    if min_len>length:
        min_len=length
print(max_len,min_len)

1491 561


In [4]:
emfit_vals=np.zeros((1491,40))
somnofy_vals=np.zeros((1491,40))
psg_vals=np.zeros((1491,40))
for i in range(len(trainIDs)):
    s_stages = read_patient_data(PARTICIPANT_IDS[trainIDs[i]])
    rows=len(s_stages["sleep_stage_num_psg"].values)
    n_loop=max_len-rows
    if n_loop!=0:
        per_data=math.floor(rows/n_loop)
        if per_data==0:
            per_data=1
    i_th=0
    increment="5"
    for j in range(n_loop):
        if i_th >= rows:
            i_th=0
            increment='8'
        a=s_stages.iloc[i_th]
        row=s_stages.index.values[i_th]
        row=row[:18]+increment+row[19:]
        s_stages.loc[row]=a
        i_th+=per_data
    sorted_sleep=s_stages.sort_index()
    emfit_vals[:,i]=sorted_sleep["sleep_stage_num_emfit"].values
    somnofy_vals[:,i]=sorted_sleep["sleep_stage_num_somnofy"].values
    psg_vals[:,i]=sorted_sleep["sleep_stage_num_psg"].values   

# Method 1 
## Mean Values for emfit,somnofy,psg - all rounded

In [5]:
psg=np.zeros(1491).reshape(1491,1)
for i in range(1491):
    psg[i]=round(np.mean(psg_vals[i,:]))
emfit_mean=np.zeros(1491).reshape(1491,1)
for i in range(1491):
    emfit_mean[i]=np.mean(emfit_vals[i,:])
somnofy_mean=np.zeros(1491).reshape(1491,1)
for i in range(1491):
    somnofy_mean[i]=np.mean(somnofy_vals[i,:])

w_m1,loss_m1=mse_gd(emfit_mean+1,somnofy_mean+1,psg+1, max_iters=1500, gamma=0.005,w0=True)

## Method 2
## psg most occurant, emfit and somnofy mean

In [6]:
psg_most_occ=np.zeros(1491).reshape(1491,1)
for i in range(1491):
    counts = np.bincount(psg_vals[i,:].astype(int))
    psg_most_occ[i]=np.argmax(counts)    

w_m2,loss_m2=mse_gd(emfit_mean+1,somnofy_mean+1,psg_most_occ+1, max_iters=1500, gamma=0.005,w0=True)

# Method 3

In [7]:
loss=100
num_of_update=0
w_m3=np.zeros((2,1), dtype=float)
w = np.zeros((2,1), dtype=float)
step=0.002
while w[0] <=0.6:
    w[1]=0
    while w[1] <=0.6:
        e=np.zeros((1491,39))
        for i in range(39):
            e[:,i]=(psg_vals[:,i].reshape(1491,1)-np.c_[emfit_vals[:,i],somnofy_vals[:,i]].reshape(1491,2)@w).reshape(1491,)
        mse=np.zeros((39,1))
        for i in range(39):
            mse[i]=1/2/1491*e[:,i].T@e[:,i]
        average_mse=np.mean(mse)
        if average_mse<loss:
            num_of_update+=1
            loss=average_mse
            w_m3[0]=w[0]
            w_m3[1]=w[1]
        w[1]+=step
    w[0]+=step

# Method 5

In [8]:
acc_per_somnofy_ss0=np.zeros(40)
acc_per_somnofy_ss1=np.zeros(40)
acc_per_somnofy_ss2=np.zeros(40)
acc_per_somnofy_ss3=np.zeros(40)
acc_per_emfit_ss0=np.zeros(40)
acc_per_emfit_ss1=np.zeros(40)
acc_per_emfit_ss2=np.zeros(40)
acc_per_emfit_ss3=np.zeros(40)

for i in range(len(trainIDs)):
    subjectID = PARTICIPANT_IDS[trainIDs[i]]
    ss_patient = read_patient_data(subjectID)
    y_true=ss_patient["sleep_stage_num_psg"]
    
    for k in range(0,4):
        stages=ss_patient.loc[(ss_patient["sleep_stage_num_somnofy"]==k)]
        if k == 0:
            if not stages.empty:
                acc_per_somnofy_ss0[i]=accuracy_score(stages["sleep_stage_num_psg"],stages["sleep_stage_num_somnofy"])
            else:
                if k not in y_true.values:                    
                    acc_per_somnofy_ss0[i]=1
                else:                     
                    acc_per_somnofy_ss0[i]=0
        elif k == 1:
            if not stages.empty:
                acc_per_somnofy_ss1[i]=accuracy_score(stages["sleep_stage_num_psg"],stages["sleep_stage_num_somnofy"])
            else:
                if k not in y_true.values:                    
                    acc_per_somnofy_ss1[i]=1
                else:                     
                    acc_per_somnofy_ss1[i]=0
        elif k == 2:
            if not stages.empty:
                acc_per_somnofy_ss2[i]=accuracy_score(stages["sleep_stage_num_psg"],stages["sleep_stage_num_somnofy"])
            else:
                if k not in y_true.values:                    
                    acc_per_somnofy_ss2[i]=1
                else:                     
                    acc_per_somnofy_ss2[i]=0
        elif k == 3:
            if not stages.empty:
                acc_per_somnofy_ss3[i]=accuracy_score(stages["sleep_stage_num_psg"],stages["sleep_stage_num_somnofy"])
            else:
                if k not in y_true.values:                    
                    acc_per_somnofy_ss3[i]=1
                else:                     
                    acc_per_somnofy_ss3[i]=0
    
    for j in range(0,4):
        stages=ss_patient.loc[(ss_patient["sleep_stage_num_emfit"]==j)]
        if j == 0:
            if not stages.empty:
                acc_per_emfit_ss0[i]=accuracy_score(stages["sleep_stage_num_psg"],stages["sleep_stage_num_emfit"])
            else:
                if j not in y_true.values:                    
                    acc_per_emfit_ss0[i]=1
                else:                     
                    acc_per_emfit_ss0[i]=0
        elif j == 1:
            if not stages.empty:
                acc_per_emfit_ss1[i]=accuracy_score(stages["sleep_stage_num_psg"],stages["sleep_stage_num_emfit"])
            else:
                if j not in y_true.values:                    
                    acc_per_emfit_ss1[i]=1
                else:                     
                    acc_per_emfit_ss1[i]=0  
        elif j == 2:
            if not stages.empty:
                acc_per_emfit_ss2[i]=accuracy_score(stages["sleep_stage_num_psg"],stages["sleep_stage_num_emfit"])
            else:
                if j not in y_true.values:                    
                    acc_per_emfit_ss2[i]=1
                else:                     
                    acc_per_emfit_ss2[i]=0
        elif j == 3:
            if not stages.empty:
                acc_per_emfit_ss3[i]=accuracy_score(stages["sleep_stage_num_psg"],stages["sleep_stage_num_emfit"])
            else:
                if j not in y_true.values:                    
                    acc_per_emfit_ss3[i]=1
                else:                     
                    acc_per_emfit_ss3[i]=0

In [9]:
print("Somnofy average accuracy for 0 :",np.average(acc_per_somnofy_ss0), "Std: ", np.std(acc_per_somnofy_ss0))
print("Somnofy average accuracy for 1 :",np.average(acc_per_somnofy_ss1), "Std: ", np.std(acc_per_somnofy_ss1))
print("Somnofy average accuracy for 2 :",np.average(acc_per_somnofy_ss2), "Std: ", np.std(acc_per_somnofy_ss2))
print("Somnofy average accuracy for 3 :",np.average(acc_per_somnofy_ss3), "Std: ", np.std(acc_per_somnofy_ss3))
print("Emfit average accuracy for 0 :",np.average(acc_per_emfit_ss0), "Std: ", np.std(acc_per_emfit_ss0))
print("Emfit average accuracy for 1 :",np.average(acc_per_emfit_ss1), "Std: ", np.std(acc_per_emfit_ss1))
print("Emfit average accuracy for 2 :",np.average(acc_per_emfit_ss2), "Std: ", np.std(acc_per_emfit_ss2))
print("Emfit average accuracy for 3 :",np.average(acc_per_emfit_ss3), "Std: ", np.std(acc_per_emfit_ss3))

Somnofy average accuracy for 0 : 0.6651799442248981 Std:  0.30089200112218617
Somnofy average accuracy for 1 : 0.4264476822315352 Std:  0.3088528438526697
Somnofy average accuracy for 2 : 0.6629413338995066 Std:  0.16201527210200667
Somnofy average accuracy for 3 : 0.6502268241593309 Std:  0.2778200430967971
Emfit average accuracy for 0 : 0.42194647907175514 Std:  0.4005038987566586
Emfit average accuracy for 1 : 0.20842166395038458 Std:  0.16111066776377103
Emfit average accuracy for 2 : 0.5543939952779603 Std:  0.14800592065372112
Emfit average accuracy for 3 : 0.3719252600915176 Std:  0.18635786906960833


In [10]:
avrg_acc_somnofy=[np.average(acc_per_somnofy_ss0),np.average(acc_per_somnofy_ss1),np.average(acc_per_somnofy_ss2),np.average(acc_per_somnofy_ss3)]
std_somnofy=[np.std(acc_per_somnofy_ss0),np.std(acc_per_somnofy_ss1),np.std(acc_per_somnofy_ss2),np.std(acc_per_somnofy_ss3)]
avrg_acc_emfit=[np.average(acc_per_emfit_ss0),np.average(acc_per_emfit_ss1),np.average(acc_per_emfit_ss2),np.average(acc_per_emfit_ss3)]
std_emfit=[np.std(acc_per_emfit_ss0),np.std(acc_per_emfit_ss1),np.std(acc_per_emfit_ss2),np.std(acc_per_emfit_ss3)]

In [11]:
def m5_build_ss(emfit,somnofy,avrg_acc_somnofy,std_somnofy,avrg_acc_emfit,std_emfit):
    ss_m5=np.zeros(len(emfit))

    for j in range(100):
        for i in range(len(emfit)):
            gaus_acc_somnofy=random.gauss(avrg_acc_somnofy[int(somnofy[i])],std_somnofy[int(somnofy[i])])
            gaus_acc_emfit=random.gauss(avrg_acc_emfit[int(emfit[i])],std_emfit[int(emfit[i])])
            value=gaus_acc_somnofy/(gaus_acc_somnofy+gaus_acc_emfit)
            rand_num=random.randint(0,100)

            if rand_num/100 <= value:
                ss_m5[i]+=somnofy[i]
            else:
                ss_m5[i]+=emfit[i]
    for i in range(len(psg)):
        ss_m5[i]=round(ss_m5[i]/100)
    return(ss_m5)   

# Method 4

In [12]:
conf_somnofy=np.zeros((4,4))
conf_emfit=np.ones((4,4))
for i in range(len(trainIDs)):
    subjectID = PARTICIPANT_IDS[trainIDs[i]]
    ss_patients = read_patient_data(subjectID)
    psg=ss_patients["sleep_stage_num_psg"]
    
    conf_somnofy+=confusion_matrix(psg,ss_patients["sleep_stage_num_somnofy"])
    conf_emfit+=confusion_matrix(psg,ss_patients["sleep_stage_num_emfit"])

for i in range(len(conf_somnofy)):
    for j in range(len(conf_somnofy[0])):
        conf_somnofy[i][j]=round(conf_somnofy[i][j]/len(trainIDs))
for i in range(len(conf_emfit)):
    for j in range(len(conf_emfit[0])):
        conf_emfit[i][j]=round(conf_emfit[i][j]/len(trainIDs))
print(conf_somnofy)
print(conf_emfit)

[[ 77.  18.  54.   6.]
 [  9.  70.  23.   2.]
 [ 45.  58. 279.  41.]
 [  7.   5.  49.  89.]]
[[ 15.  52.  74.  15.]
 [  3.  42.  52.   7.]
 [  5.  86. 260.  73.]
 [  1.  14.  77.  59.]]


In [13]:
when_emfit_0=[]
when_emfit_1=[]
when_emfit_2=[]
when_emfit_3=[]
when_somnofy_0=[]
when_somnofy_1=[]
when_somnofy_2=[]
when_somnofy_3=[]

for i in range(4):
    sum=0
    for j in range(4):
        sum+=conf_emfit[j][i]
    for j in range(4):
        if i==0:
            when_emfit_0.append(conf_emfit[j][i]/sum)
        elif i==1:
            when_emfit_1.append(conf_emfit[j][i]/sum)
        elif i==2:
            when_emfit_2.append(conf_emfit[j][i]/sum)
        elif i==3:
            when_emfit_3.append(conf_emfit[j][i]/sum)
        
for i in range(4):
    sum=0
    for j in range(4):
        sum+=conf_somnofy[j][i]
    for j in range(4):
        if i==0:
            when_somnofy_0.append(conf_somnofy[j][i]/sum)
        elif i==1:
            when_somnofy_1.append(conf_somnofy[j][i]/sum)
        elif i==2:
            when_somnofy_2.append(conf_somnofy[j][i]/sum)
        elif i==3:
            when_somnofy_3.append(conf_somnofy[j][i]/sum)

In [14]:
def change_input(emfit,somnofy):
    ss_somnofy_new=np.zeros(len(emfit))
    ss_emfit_new=np.zeros(len(emfit))
    
    for j in range(100):
        for i in range(len(somnofy)):
            randnum=random.randint(0,100)/100
            somnofy_val=somnofy[i]
            if somnofy_val==0:
                limit1=when_somnofy_0[0]
                limit2=limit1+when_somnofy_0[1]
                limit3=limit2+when_somnofy_0[2]
                if randnum <=limit1:
                    ss_somnofy_new[i]+=0
                elif limit1<randnum <=limit2:
                    ss_somnofy_new[i]+=1
                elif limit2<randnum <=limit3:
                    ss_somnofy_new[i]+=2
                else:
                    ss_somnofy_new[i]+=3
            elif somnofy_val==1:
                limit1=when_somnofy_1[0]
                limit2=limit1+when_somnofy_1[1]
                limit3=limit2+when_somnofy_1[2]
                if randnum <=limit1:
                    ss_somnofy_new[i]+=0
                elif limit1<randnum <=limit2:
                    ss_somnofy_new[i]+=1
                elif limit2<randnum <=limit3:
                    ss_somnofy_new[i]+=2
                else:
                    ss_somnofy_new[i]+=3
            elif somnofy_val==2:
                limit1=when_somnofy_2[0]
                limit2=limit1+when_somnofy_2[1]
                limit3=limit2+when_somnofy_2[2]
                if randnum<=limit1:
                    ss_somnofy_new[i]+=0
                elif limit1<randnum <=limit2:
                    ss_somnofy_new[i]+=1
                elif limit2<randnum<=limit3:
                    ss_somnofy_new[i]+=2
                else:
                    ss_somnofy_new[i]+=3
            elif somnofy_val==3:
                limit1=when_somnofy_3[0]
                limit2=limit1+when_somnofy_3[1]
                limit3=limit2+when_somnofy_3[2]
                if randnum<=limit1:
                    ss_somnofy_new[i]+=0
                elif limit1<randnum<=limit2:
                    ss_somnofy_new[i]+=1
                elif limit2<randnum<=limit3:
                    ss_somnofy_new[i]+=2
                else:
                    ss_somnofy_new[i]+=3

        for i in range(len(emfit)):
            randnum=random.randint(0,100)/100
            emfit_val=emfit[i]
            if emfit_val==0:
                limit1=when_emfit_0[0]
                limit2=limit1+when_emfit_0[1]
                limit3=limit2+when_emfit_0[2]
                if randnum <=limit1:
                    ss_emfit_new[i]+=0
                elif limit1<randnum <=limit2:
                    ss_emfit_new[i]+=1
                elif limit2<randnum <=limit3:
                    ss_emfit_new[i]+=2
                else:
                    ss_emfit_new[i]=3
            if emfit_val==1:
                limit1=when_emfit_1[0]
                limit2=limit1+when_emfit_1[1]
                limit3=limit2+when_emfit_1[2]
                if randnum <=limit1:
                    ss_emfit_new[i]+=0
                elif limit1<randnum <=limit2:
                    ss_emfit_new[i]+=1
                elif limit2<randnum <=limit3:
                    ss_emfit_new[i]+=2
                else:
                    ss_emfit_new[i]+=3
            if emfit_val==2:
                limit1=when_emfit_2[0]
                limit2=limit1+when_emfit_2[1]
                limit3=limit2+when_emfit_2[2]
                if randnum<=limit1:
                    ss_emfit_new[i]+=0
                elif limit1<randnum<=limit2:
                    ss_emfit_new[i]+=1
                elif limit2<randnum<=limit3:
                    ss_emfit_new[i]+=2
                else:
                    ss_emfit_new[i]+=3
            if emfit_val==3:
                limit1=when_emfit_3[0]
                limit2=limit1+when_emfit_3[1]
                limit3=limit2+when_emfit_3[2]
                if randnum<=limit1:
                    ss_emfit_new[i]+=0
                elif limit1<randnum<=limit2:
                    ss_emfit_new[i]+=1
                elif limit2<randnum<=limit3:
                    ss_emfit_new[i]+=2
                else:
                    ss_emfit_new[i]+=3
    for i in range(len(ss_emfit_new)):
        ss_emfit_new[i]=round(ss_emfit_new[i]/100)
    for i in range(len(ss_somnofy_new)):
        ss_somnofy_new[i]=round(ss_somnofy_new[i]/100)
    
    return ss_emfit_new,ss_somnofy_new

# Scores

In [20]:
Radar=np.zeros(10)
Mattress=np.zeros(10)

method1=np.zeros(10)

method2=np.zeros(10)

method3=np.zeros(10)

method4=np.zeros(10)

method5=np.zeros(10)

for i in range(len(testIDs)): 
    ss = read_patient_data(PARTICIPANT_IDS[testIDs[i]])
    radar=ss["sleep_stage_num_somnofy"]
    psg=ss["sleep_stage_num_psg"]
    mat=ss["sleep_stage_num_emfit"]

    ss_m1=build_new_ss(w_m1,mat+1,radar+1,True)
    
    ss_m2=build_new_ss(w_m2,mat+1,radar+1,True)
    
    ss_m3=build_new_ss(w_m3,mat,radar)
    
    mat_new,radar_new=change_input(mat,radar)
    ss_m4=build_new_ss(w_m2,mat_new+1,radar_new+1,True)

    ss_m5=m5_build_ss(mat,radar,avrg_acc_somnofy,std_somnofy,avrg_acc_emfit,std_emfit)
      
    Radar[i]=balanced_accuracy_score(psg,radar)
    Mattress[i]=balanced_accuracy_score(psg,mat)
    
    method1[i]=balanced_accuracy_score(psg,ss_m1)
    
    method2[i]=balanced_accuracy_score(psg,ss_m2)
    
    method3[i]=balanced_accuracy_score(psg,ss_m3)
    
    method4[i]=balanced_accuracy_score(psg,ss_m4)
    
    method5[i]=balanced_accuracy_score(psg,ss_m5)

In [21]:
print("Radar: ", np.mean(Radar))
print("Mat: ", np.mean(Mattress))

print("Method 1: ", np.mean(method1))

print("Method 2: ", np.mean(method2))

print("Method 3: ", np.mean(method3))

print("Method 4: ", np.mean(method4))

print("Method 5: ", np.mean(method5))

Radar:  0.6531389332881066
Mat:  0.4117312747694902
Method 1:  0.47141583738714815
Method 2:  0.47419369903294617
Method 3:  0.5047299302563365
Method 4:  0.4231366754300449
Method 5:  0.48306812246340697
