# Machine Learning Model Implementations
This file includes machine learning model implementations and optimization steps.
The models used in order is as follows:
1. KNN classifier
2. ...


### Import Packages and Load Dataset

Labels come from 2 different PSG systems: Remlogic and Somnomedics. Sleep stage labels are as follows:

0 = Awake = SLEEP-S0 \
1 = REM   = SLEEP-REM \
2 = Light = SLEEP-S1 and  SLEEP-S2 \
3 = Deep  = SLEEP-S3 

EMFIT is the piezoelectric mat and Somnofy is the radar.

In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

import numpy as np
from helpers import *

In [2]:
subjectID = PARTICIPANT_IDS[1]
sleep_stages, nan_counts = impute_data(subjectID)
print(nan_counts)

(0, 0, 0)


In [7]:
labels = sleep_stages["sleep_stage_num_psg"]
features = sleep_stages.drop(columns="sleep_stage_num_psg")
size = sleep_stages.shape[0]
divide_ind = int(size*.7)

### KNN Classifier

In [16]:
knn_classifier = KNeighborsClassifier(n_neighbors=10)
knn_classifier.fit(features[:divide_ind], labels[:divide_ind])

KNeighborsClassifier(n_neighbors=10)

In [17]:
preds = knn_classifier.predict(features[divide_ind:])

In [18]:
# Accuracy score 
print(accuracy_score(preds, labels[divide_ind:]))

# Confusion Matrix and Classification Report 
print(confusion_matrix(preds, labels[divide_ind:]))
print(classification_report(preds, labels[divide_ind:]))

0.38372093023255816
[[14  0  8  0]
 [95  0  0  0]
 [ 4 20 85  0]
 [ 0  4 28  0]]
              precision    recall  f1-score   support

         0.0       0.12      0.64      0.21        22
         1.0       0.00      0.00      0.00        95
         2.0       0.70      0.78      0.74       109
         3.0       0.00      0.00      0.00        32

    accuracy                           0.38       258
   macro avg       0.21      0.35      0.24       258
weighted avg       0.31      0.38      0.33       258



/Users/elifkurtay/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/elifkurtay/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/elifkurtay/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
